var cantidadDeVentanasEnMiCasa = 4;
var soyHumano = true;
var miGustoDePizzaPreferido = "Margarita";
var varios = false;
console.log ("La cantidad de ventanas en mi casa es " + cantidadDeVentanasEnMiCasa);
console.log('\n');
console.log ("Soy humano " + soyHumano);
console.log('\n');
console.log ("Mi gusto de Pizza preferido es " + miGustoDePizzaPreferido);
console.log('\n');
console.log ("Valores con la misma variable " + varios);
console.log('\n');
varios = "Hola";
console.log ("Valores varios con la misma variable " + varios);
console.log('\n');
varios = 0;
console.log ("Valores con la misma variable " + varios);
console.log('\n');
varios = "Minions";
console.log ("Valores con la misma variable " + varios);